<!-- Created by Swapnil Srivastava-->

<!DOCTYPE html>
<html>
    <head>
        <title>Page Title</title>
    </head>
    <body>
    <section id="container"></section>
    <!-- INSPIRED BY QWERTY'S PROFILE PIC -->
        <script>
            var n=5
            var body=document.getElementById('container')
            for(x=0;x<=n;x++){
                div=document.createElement("div")
                div.style.transform="rotateX(90deg) translateZ("+((x*-40)+100)+"px) translateY(-100px) translateX(0px)"
                div.innerHTML="01010011<wbr/>10001010<wbr>10111001<wbr>010000101<wbr>110110010<wbr/>1011011001<wbr/>101110010<wbr>101101001<wbr>0100110001<wbr>".repeat(15)
                //div.style.background="red"
                body.appendChild(div)
            }
             for(y=0;y<=n;y++){
                div=document.createElement("div")
                div.style.transform="rotateY(90deg) translateZ("+((y*-40)+100)+"px) translateX(100px) translateY(0px)"
                div.innerHTML="01010011<wbr/>10001010<wbr>10111001<wbr>010000101<wbr>110110010<wbr/>1011011001<wbr/>101110010<wbr>101101001<wbr>0100110001<wbr>".repeat(15)
               // div.style.background="green"
                body.appendChild(div)
            }
            for(z=0;z<=n;z++){
                div=document.createElement("div")
                div.style.transform="translateZ("+((z*-40))+"px)"
                div.innerHTML="01010011<wbr/>10001010<wbr>10111001<wbr>010000101<wbr>110110010<wbr/>1011011001<wbr/>101110010<wbr>101101001<wbr>0100110001<wbr>".repeat(15)
                body.appendChild(div)
            }
        </script>
    </body>
</html>
